var listItem = [
    {   id: 1,
        brand: 'Marshall',
        photo: '../assets/img/Products/Marshall/Motif-ANC.png',
        model: 'Marshal Motif A.N.C',
        price: 4990000,
        form: 'In-ear',
        isWireless: 'true',
        isGamingType: 'false',
        rate: 4,
        discount: 0.2
    },
    {   id: 2,
        brand: 'SONY',
        photo: '../assets/img/Products/SONY/XBA-N1AP.png',
        model: 'SONY XBA-N1AP',
        price: 4990000,
        form: 'In-ear',
        isWireless: 'false',
        isGamingType: 'false',
        rate: 3.9,
        discount: 0.25
    },
    {   id: 3,
        brand: 'Apple',
        photo: '../assets/img/Products/Apple/AirPods-Max.png',
        model: 'Apple AirPods Max',
        price: 13900000,
        form: 'Over-ear',
        isWireless: 'true',
        isGamingType: 'false',
        rate: 4.2,
        discount: 0.35
    },
    {   id: 4,
        brand: 'ASUS',
        photo: '../assets/img/Products/ASUS/ROG-Cetra-True-Wireless.png',
        model: 'ASUS ROG Cetra True Wireless',
        price: 1890000,
        form: 'In-ear',
        isWireless: 'true',
        isGamingType: 'true',
        rate: 4.9,
        discount: 0
    },
    {   id: 5,
        brand: 'JBL',
        photo: '../assets/img/Products/JBL/Quantum-400.png',
        model: 'JBL Quantum 400',
        price: 1990000,
        form: 'Over-ear',
        isWireless: 'false',
        isGamingType: 'true',
        rate: 4.5,
        discount: 0.15
    },
    {   id: 6,
        brand: 'JBL',
        photo: '../assets/img/Products/JBL/T500BT.png',
        model: 'JBL T500BT',
        price: 1090000,
        form: 'On-ear',
        isWireless: 'true',
        isGamingType: 'false',
        rate: 3.5,
        discount: 0.1
    },
    {   id: 7,
        brand: 'KZ',
        photo: '../assets/img/Products/KZ/EDX-Pro.png',
        model: 'KZ EDX Pro',
        price: 250000,
        form: 'In-ear',
        isWireless: 'false',
        isGamingType: 'false',
        rate: 2.5,
        discount: 0
    },
    {   id: 8,
        brand: 'Marshall',
        photo: '../assets/img/Products/Marshall/Minor-III.png',
        model: 'Marshall Minor III Black',
        price: 3290000,
        form: 'In-ear',
        isWireless: 'true',
        isGamingType: 'false',
        rate: 4.2,
        discount: 0
    },
    {   id: 9,
        brand: 'Apple',
        photo: '../assets/img/Products/Apple/EarPods-Lightning.png',
        model: 'Apple EarPods Lightning',
        price: 590000,
        form: 'In-ear',
        isWireless: 'false',
        isGamingType: 'false',
        rate: 4,
        discount: 0.15
    },
    {   id: 10,
        brand: 'SONY',
        photo: '../assets/img/Products/SONY/WH-XB910N.png',
        model: 'SONY WH-XB910N',
        price: 4590000,
        form: 'Over-ear',
        isWireless: 'true',
        isGamingType: 'false',
        rate: 4.6,
        discount: 0.3
    },
    {   id: 11,
        brand: 'ASUS',
        photo: '../assets/img/Products/ASUS/TUF-H3.png',
        model: 'ASUS TUF H3',
        price: 990000,
        form: 'Over-ear',
        isWireless: 'false',
        isGamingType: 'true',
        rate: 5,
        discount: 0.1
    },
    {   id: 12,
        brand: 'SONY',
        photo: '../assets/img/Products/SONY/MDR-1AM2.png',
        model: 'SONY MDR-1AM2',
        price: 6990000,
        form: 'Over-ear',
        isWireless: 'false',
        isGamingType: 'false',
        rate: 5,
        discount: 0.3
    },
    {   id: 13,
        brand: 'KZ',
        photo: '../assets/img/Products/KZ/ZSN-Pro-X.png',
        model: 'KZ ZSN Pro X',
        price: 490000,
        form: 'In-ear',
        isWireless: 'false',
        isGamingType: 'false',
        rate: 5,
        discount: 0
    },
    {   id: 14,
        brand: 'ASUS',
        photo: '../assets/img/Products/ASUS/ROG-Strix-Go.png',
        model: 'ASUS ROG Strix Go',
        price: 1990000,
        form: 'Over-ear',
        isWireless: 'false',
        isGamingType: 'true',
        rate: 4.1,
        discount: 0
    },
    {   id: 15,
        brand: 'Marshall',
        photo: '../assets/img/Products/Marshall/Major-IV.png',
        model: 'Marshall Major IV Brown',
        price: 3690000,
        form: 'On-ear',
        isWireless: 'true',
        isGamingType: 'false',
        rate: 4.7,
        discount: 0.15
    },
    {   id: 16,
        brand: 'Marshall',
        photo: '../assets/img/Products/Marshall/Mode-EQ.png',
        model: 'Marshall Mode EQ',
        price: 1990000,
        form: 'In-ear',
        isWireless: 'false',
        isGamingType: 'false',
        rate: 3.7,
        discount: 0.1
    },
    {   id: 17,
        brand: 'JBL',
        photo: '../assets/img/Products/JBL/Quantum-50.png',
        model: 'JBL Quantum 50',
        price: 690000,
        form: 'In-ear',
        isWireless: 'false',
        isGamingType: 'true',
        rate: 3.6,
        discount: 0
    },
    {   id: 18,
        brand: 'JBL',
        photo: '../assets/img/Products/JBL/T600BTNC.png',
        model: 'JBL T600BTNC',
        price: 1550000,
        form: 'On-ear',
        isWireless: 'true',
        isGamingType: 'false',
        rate: 5,
        discount: 0
    },
    {   id: 19,
        brand: 'Apple',
        photo: '../assets/img/Products/Apple/AirPods-Pro.png',
        model: 'Apple AirPods Pro',
        price: 7990000,
        form: 'In-ear',
        isWireless: 'true',
        isGamingType: 'false',
        rate: 4.3,
        discount: 0.25
    },
    {   id: 20,
        brand: 'SONY',
        photo: '../assets/img/Products/SONY/WI-C100.png',
        model: 'SONY WI-C100',
        price: 650000,
        form: 'In-ear',
        isWireless: 'true',
        isGamingType: 'false',
        rate: 4.4,
        discount: 0
    },
    {   id: 21,
        brand: 'Marshall',
        photo: '../assets/img/Products/Marshall/Monitor-II-ANC.png',
        model: 'Marshall Monitor II A.N.C',
        price: 3190000,
        form: 'In-ear',
        isWireless: 'true',
        isGamingType: 'false',
        rate: 3.2,
        discount: 0.1
    },
    {   id: 22,
        brand: 'ASUS',
        photo: '../assets/img/Products/ASUS/ROG-Cetra-2-Core.png',
        model: 'ASUS ROG Cetra 2 Core',
        price: 1290000,
        form: 'In-ear',
        isWireless: 'false',
        isGamingType: 'false',
        rate: 4.8,
        discount: 0.1
    },
    {   id: 23,
        brand: 'SONY',
        photo: '../assets/img/Products/SONY/MDR-ZX110AP.png',
        model: 'SONY MDR-ZX110AP',
        price: 540000,
        form: 'On-ear',
        isWireless: 'false',
        isGamingType: 'false',
        rate: 3.9,
        discount: 0
    },
]

const searchResultContainer = document.querySelector(".search-result .search-result-list");
var searchingInput = localStorage.getItem("SearchingInput").toLowerCase();

if(searchResultContainer) {
    searchResultContainer.innerHTML = `<p class="text-center not-found">Không tìm thấy sản phẩm phù hợp</p>`
    for (let i = 0; i < listItem.length; i++) {
        if (listItem[i].model.toLowerCase().search(searchingInput) != -1) {
            const notFoundMessage = document.querySelector(".not-found");
            if(notFoundMessage) {
                notFoundMessage.remove();
            }
            searchResultContainer.innerHTML +=`
            <div class="product-item-container col-6 col-sm-4 col-md-3 col-lg-2">
                 <div class="product-item p-2" id="${i}">
                    <img src="${listItem[i].photo}" alt="">
                    <h5 class="m-0 mt-2">${listItem[i].model}</h5>
                    <p class="m-0 mt-2 d-flex align-items-center">${listItem[i].rate}
                        <img src="../assets/img/star-rate.png" class="star-rate">
                    </p>
                    <h5 class="m-0 mt-2">${new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(listItem[i].price)}</h5>
                </div>
            </div>
            `;
        }
    }
}